# 1. Tensor	properties - ranks, shapes and types

In [4]:
## tensor rank
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]])
print tens1
sess = tf.Session()
print sess.run(tens1)[1,1,0]

Tensor("Const_3:0", shape=(2, 2, 2), dtype=int32)
5


# 2. Creating new tensor

In [10]:
import numpy as np
x = tf.constant(np.random.rand(10).astype(np.float32))
y = tf.constant([1,2,3])
z_data = np.array([[1,2,3],[2,3,4]])
z = tf.convert_to_tensor(z_data, dtype=tf.float32)
print sess.run(x)
print sess.run(y)
print sess.run(z)

[ 0.34128672  0.1970298   0.83438283  0.43739271  0.86360323  0.09209151
  0.43836933  0.28598422  0.9213565   0.04425582]
[1 2 3]
[[ 1.  2.  3.]
 [ 2.  3.  4.]]
