# 1. Tensor	properties - ranks, shapes and types

In [4]:
## tensor rank
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]])
print tens1
sess = tf.Session()
print sess.run(tens1)[1,1,0]

Tensor("Const_3:0", shape=(2, 2, 2), dtype=int32)
5


# 2. Creating new tensor

In [4]:
import tensorflow as tf
import numpy as np
x = tf.constant(np.random.rand(10).astype(np.float32))
y = tf.constant([1,2,3])
z_data = np.array([[1,2,3],[2,3,4]])
z = tf.convert_to_tensor(z_data, dtype=tf.float32)

sess = tf.Session()
print sess.run(x)
print sess.run(y)
print sess.run(z)

[ 0.86361557  0.7258231   0.08961751  0.75023025  0.57804155  0.03352209
  0.93330175  0.43788651  0.48649251  0.74827981]
[1 2 3]
[[ 1.  2.  3.]
 [ 2.  3.  4.]]


# 3. Simple matrix operation

In [14]:
import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.constant([[2, 5, 3, -5],
                [0, 3, -2, 5],
                [4, 3, 5, 3],
                [6, 1, 4, 0]])
y = tf.constant([[4, -7, 4, -3, 4],
                [6, 4, -7, 4, 7],
                [2, 3, 2, 1, 4],
                [1, 5, 5, 5, 2]])
floatx = tf.constant([[2., 5., 3., -5.],
                    [0., 3., -2., 5.],
                    [4., 3., 5., 3.],
                    [6., 1., 4., 0.]])
print "x transpose: \n", tf.transpose(x).eval()
print "matmul(x,y): \n", tf.matmul(x, y).eval()
print "floatx determinant:", tf.matrix_determinant(floatx).eval()
print "floatx inverse: \n", tf.matrix_inverse(floatx).eval()
print "solve matrix: \n", tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval()

x transpose: 
[[ 2  0  4  6]
 [ 5  3  3  1]
 [ 3 -2  5  4]
 [-5  5  3  0]]
matmul(x,y): 
[[ 39 -10 -46  -8  45]
 [ 19  31   0  35  23]
 [ 47  14  20  20  63]
 [ 38 -26  25 -10  47]]
floatx determinant: 818.0
floatx inverse: 
[[-0.00855745  0.10513447 -0.18948655  0.29584354]
 [ 0.12958434  0.12224938  0.01222495 -0.05134475]
 [-0.01955992 -0.18826404  0.28117359 -0.18092909]
 [-0.08557458  0.05134474  0.10513448 -0.0415648 ]]
solve matrix: 
[[ 0.202934  ]
 [ 0.21271393]
 [-0.10757945]
 [ 0.02933985]]


# 4. Reduction
Reduction is an operation that applies an operation across one of the tensor's dimensions, leaving it with one less dimension.

In [23]:
import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.constant([[1, 2, 3],
                [3, 2, 1],
                [-1, -2, -3]])
boolean_tensor = tf.constant([[True, False, True],
                              [False, False, True],
                              [True, False, False]])
print "reduce_prod: ", tf.reduce_prod(x, reduction_indices=1).eval()
print "reduce_min: ", tf.reduce_min(x, reduction_indices=1).eval()
print "reduce_max: ", tf.reduce_max(x, reduction_indices=1).eval()
print "reduce_mean: ", tf.reduce_mean(x, reduction_indices=1).eval()
print "reduce_all: ", tf.reduce_all(boolean_tensor, reduction_indices=1).eval()
print "reduce_any: ", tf.reduce_any(boolean_tensor, reduction_indices=1).eval()

reduce_prod:  [ 6  6 -6]
reduce_min:  [ 1  1 -3]
reduce_max:  [ 3  3 -1]
reduce_mean:  [ 2  2 -2]
reduce_all:  [False False False]
reduce_any:  [ True  True  True]
